export const COMMON_ACTION_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  SET_ALERT_REQ: '_SET_ALERT_REQ',
  SET_ALERT: '_SET_ALERT',
  CLEAR_ALERT: '_CLEAR_ALERT',
}

export const AUTH_ACTION_TYPES = {
  AUTHORIZE_USER: 'AUTHORIZE_USER',
  FETCH_AUTHORIZE_USER: 'FETCH_AUTHORIZE_USER',
  FETCH_AUTHORIZE_USER_ROLES: 'FETCH_AUTHORIZE_USER_ROLES',
  SET_ACTIVE_USER_ROLE: 'SET_ACTIVE_USER_ROLE',
  FETCH_ACTIVE_USER_ROLE: 'FETCH_ACTIVE_USER_ROLE',
  LOGOUT: 'LOGOUT',
}

export const BANNER_ACTION_TYPES = {
  POST_BANNER: 'POST_BANNER',
  GET_BANNER_LIST: 'GET_BANNER_LIST',
  UPDATE_BANNER: 'UPDATE_BANNER',
  DELETE_BANNER: 'DELETE_BANNER',
}

export const TEAM_ACTION_TYPES = {
  POST_TEAM: 'POST_TEAM',
  GET_TEAM_LIST: 'GET_TEAM_LIST',
  UPDATE_TEAM: 'UPDATE_TEAM',
}

export const APPLICATION_ACTION_TYPES = {
  GET_APPLICATION_LIST: 'GET_APPLICATION_LIST',
}
export const USER_ACTION_TYPES = {
  CREATE_USER: 'CREATE_USER',
  GET_USER_LIST: 'GET_USER_LIST',
  GET_USER_DESIGNATIONS: 'GET_USER_DESIGNATIONS',
  UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
  GET_USER_BRIEF_LIST: 'GET_USER_BRIEF_LIST',
  UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
}

export const RESIGNATION_ACTION_TYPES = {
  POST_RESIGNATION: 'POST_RESIGNATION',
  GET_RESIGNATION_LIST: 'GET_RESIGNATION_LIST',
  POST_COMMENT: 'POST_COMMENT',
  GET_STATUS_LIST: 'GET_STATUS_LIST',
  UPDATE_RESIGNATION: 'UPDATE_RESIGNATION',
  CREATE_USER: 'CREATE_USER',
  GET_USER_LIST: 'GET_USER_LIST',
  GET_USER_DESIGNATIONS: 'GET_USER_DESIGNATIONS',
  UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
}
export const SBU_ACTION_TYPES = {
  POST_SBU: 'POST_SBU',
  GET_SBU_LIST: 'GET_SBU_LIST',
  UPDATE_SBU: 'UPDATE_SBU',
  GET_SBU_HIERARCHY: 'GET_SBU_HIERARCHY',
}

export const CLIENT_ACTION_TYPES = {
  POST_CLIENT: 'POST_CLIENT',
  GET_CLIENT_LIST: 'GET_CLIENT_LIST',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
}

export const FLYER_ACTION_TYPES = {
  GET_FLYER_TAGS: 'GET_FLYER_TAGS',
  POST_FLYER: 'POST_FLYER',
  GET_FLYER_LIST: 'GET_FLYER_LIST',
  DELETE_FLYER: 'DELETE_FLYER',
}

export const BADGE_ACTION_TYPES = {
  POST_BADGE: 'POST_BADGE',
  GET_BADGE_LIST: 'GET_BADGE_LIST',
  UPDATE_BADGE: 'UPDATE_BADGE',
  POST_ALLOCATION: 'POST_ALLOCATION',
  GET_ALLOCATION_LIST: 'GET_ALLOCATION_LIST',
  UPDATE_ALLOCATION: 'UPDATE_ALLOCATION',
  GET_USER_BRIEF: 'GET_USER_BRIEF',
  REMOVE_BADGE_ALLOCATION: 'REMOVE_BADGE_ALLOCATION',
}

export const ROLE_ACTION_TYPES = {
  GET_USERROLE_LIST: 'GET_USERROLE_LIST',
  GET_FEATURE_LIST: 'GET_FEATURE_LIST',
  UPDATE_PERMISSION: 'UPDATE_PERMISSION',
  CLEAR_USER_ROLES: 'CLEAR_USER_ROLES',
}

export const ENTITLEMENTS_ACTION_TYPES = {
  GET_USER_ENTITLEMENTS: 'GET_USER_ENTITLEMENTS',
  SET_USER_ENTITLEMENTS: 'SET_USER_ENTITLEMENTS',
  SAVE_USER_ENTITLEMENTS: 'SAVE_USER_ENTITLEMENTS',
}

export const LEAVES_ACTION_TYPES = {
  GET_ALL_LEAVE_COUNTS: 'GET_ALL_LEAVE_COUNTS',
  GET_USER_LEAVE_COUNTS: 'GET_USER_LEAVE_COUNTS',
  UPDATE_LEAVE_COUNTS: 'UPDATE_LEAVE_COUNTS',
  ADD_LEAVE_COUNT: 'ADD_LEAVE_COUNT',
}
