import { APP_ROUTES } from '.'

export const APP_TABLE_CONFIGS = {
  DEFAULT_ROWS_PER_PAGE_OPTIONS: [10, 25],
  DEFAULT_ROWS_PER_PAGE: 10,
  BADGE_ROWS_PER_PAGE_OPTIONS: [4, 8],
  BADGE_DEFAULT_ROWS_PER_PAGE: 4,
}
export const BROWSER_STORAGE_CONFIGS = {
  MAX_COOKIE_SIZE: 4000,
  MAX_LOCAL_STORAGE_SIZE: 4.5e6,
}

export const BANNER_IMAGE_CONFIGS = {
  MAX_IMAGE_SIZE: 1048576, // 1MB in bytes
  IMAGE_RATIO_TYPE1: {
    WIDTH: 1920,
    HEIGHT: 1080,
  },
  IMAGE_RATIO_TYPE2: {
    WIDTH: 1280,
    HEIGHT: 720,
  },
  FLYER_IMAGE_TYPE: {
    WIDTH: 800,
    HEIGHT: 600,
  },
  ALLOWED_FORMATS: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'],
}

export const BADGE_IMAGE_CONFIGS = {
  MAX_IMAGE_SIZE: 1048576, // 1MB in bytes
  IMAGE_RATIO_TYPE1: {
    WIDTH: 500,
    HEIGHT: 500,
  },
  IMAGE_RATIO_TYPE2: {
    WIDTH: 250,
    HEIGHT: 250,
  },
  ALLOWED_FORMATS: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'],
}

export const APPLICATION_IDS = {
  HERA: 4,
  ATHENA: 2,
  HERMES: 1,
  DASHBOARD: 5,
  DEMETER: 6,
  CORE: 3,
}

export const LEAVE_TYPE_IDS = {
  ANNUAL_LEAVE: 1,
  LIEU_LEAVE: 2,
  CASUAL_LEAVE: 3,
}

export const APP_USER_ROLES = {
  SUPER_ADMIN: 'Super Admin',
}

export const APP_FEATURE_KEYS = {
  VIEW_ALL_ALLOCATION: 'FE001',
  CREATE_NEW_ALLOCATION: 'FE002',
  UPDATE_ALLOCATION: 'FE003',
  DEALLOCATION: 'FE004',
  VIEW_OWN_ALLOCATIONS: 'FE005',
  VIEW_ALL_SBU: 'FE006',
  CREATE_NEW_SBU: 'FE007',
  UPDATE_SBU: 'FE008',
  VIEW_ALL_CLIENTS: 'FE009',
  CREATE_NEW_CLIENT: 'FE010',
  UPDATE_CLIENT: 'FE011',
  VIEW_ALL_PROJECTS: 'FE012',
  CREATE_NEW_PROJECT: 'FE013',
  UPDATE_PROJECT: 'FE014',
  VIEW_ALL_EXTERNAL_SUPERVISORS: 'FE015',
  CREATE_NEW_EXTERNAL_SUPERVISOR: 'FE016',
  UPDATE_EXTERNAL_SUPERVISOR: 'FE017',
  HERA_ALLOCATION_DETAIL_REPORT: 'FE018',
  HERA_PROJECT_DETAIL_REPORT: 'FE019',
  VIEW_ALL_TIME_ENTRIES: 'FE020',
  CREATE_UPDATE_ALL_TIME_ENTRY: 'FE022',
  VIEW_ALL_LEAVES: 'FE024',
  CREATE_UPDATE_ALL_LEAVE: 'FE026',
  UPDATE_LEAVE_COUNT_CONFIGURATION: 'FE028',
  ATHENA_ABSENTISM_REPORT: 'FE029',
  ATHENA_ATTENDANCE_REPORT: 'FE030',
  ATHENA_DETAILED_ATTENDANCE_REPORT: 'FE031',
  ATHENA_ATTENDANCE_SUMMARY_REPORT: 'FE032',
  ATHENA_ANNUAL_LEAVE_REPORT: 'FE033',
  MANAGE_HOLIDAY_CALENDAR: 'FE034',
  VIEW_ALL_USERS: 'FE036',
  CREATE_USER: 'FE037',
  UPDATE_USER: 'FE038',
  MANAGE_USER_ENTITLEMENTS: 'FE039',
  VIEW_ALL_BANNERS: 'FE040',
  CREATE_BANNER: 'FE041',
  UPDATE_BANNER: 'FE042',
  VIEW_ALL_RESIGNATIONS: 'FE043',
  CREATE_RESIGNATION: 'FE044',
  UPDATE_RESIGNATION: 'FE045',
  VIEW_ALL_BADGES: 'FE046',
  CREATE_BADGE: 'FE047',
  UPDATE_BADGE: 'FE048',
  CREATE_BADGE_ASSIGNMENT: 'FE049',
  VIEW_ALL_TICKET: 'FE050',
  CREATE_TICKET: 'FE051',
  REASSIGN_TICKET: 'FE052',
  VIEW_TICKET_TYPES: 'FE053',
  CREATE_TICKET_TYPE: 'FE054',
  UPDATE_TICKET_TYPE: 'FE055',
  VIEW_TICKET_SUB_TYPES: 'FE056',
  CREATE_TICKET_SUB_TYPE: 'FE057',
  UPDATE_TICKET_SUB_TYPE: 'FE058',
  HERA_DASHBOARD: 'FE059',
  USER_PROFILE: 'FE061',
  APPROVE_REJECT_LEAVE: 'FE062',
  VIEW_LEAVE_COUNT_CONFIGURATION: 'FE063',
  VIEW_TEAM_LEAVES: 'FE064',
  VIEW_ALL_LEAVES_SUMMARY: 'FE066',
  VIEW_TEAM_LEAVES_SUMMARY: 'FE067',
  ADD_LEAVE_COUNT_CONFIGURATION: 'FE068',
  VIEW_USERS_BY_ENTITLEMENT: 'FE069',
  VIEW_CALCULATE_LEAVE_COUNT_CONFIGURATION: 'FE070',
  REMOVE_BANNER: 'FE071',
  CLOSE_TICKET: 'FE073',
  VIEW_USER_ENTITLEMENTS: 'FE074',
  REPLY_TICKET: 'FE075',
  CREATE_TICKET_WITH_ASSIGNEE: 'FE077',
  REASSIGN_DIFFERENT_TEAM: 'FE079',
  VIEW_TICKET_ASSIGNEES_BY_TEAM: 'FE081',
  VIEW_OWN_ENTITLED_TEAMS: 'FE082',
  VIEW_USERS_BY_TEAM: 'FE083',
  VIEW_OWN_USER_ENTITLEMENTS: 'FE084',
  MANAGE_FEATURE_PERMISSIONS: 'FE086',
  VIEW_FLYERS: 'FE090',
  CREATE_FLYER: 'FE091',
  UPDATE_FLYER: 'FE092',
  CREATE_RESOURCE_REQUEST: 'FE093',
  UPDATE_RESOURCE_REQUEST: 'FE094',
  VIEW_RESOURCE_REQUEST: 'FE095',
  UPDATE_RESOURCE: 'FE096',
  BU_RESOURCE_REQUEST_ACTION: 'FE097',
  RM_RESOURCE_REQUEST_ACTION: 'FE098',
  PROPOSE_RESOURCE: 'FE099',
  DELETE_PROPOSED_REQUEST: 'FE100',
  CONFIRM_PROPOSED_RESOURCES: 'FE101',
  PROPOSED_RESOURCE_ACTION: 'FE102',
}

export const ALERT_CONFIGS = {
  TIMEOUT: 4000,
  ASYNC_REQ_TIMEOUT: 2000,
  AUTO_CLEAR: true,
}

export const DATE_FORMAT = 'YYYY-MM-DD'
export const DATE_FORMAT_2 = 'Do MMM of YYYY'
export const DATE_TIME_FORMAT = 'YYYY-MM-DD - HH:mm:ss'
export const DATE_TIME_FORMAT_2 = 'DD/MM/YYYY  hh:mm a'

export const BREAD_CRUMB = {
  USER_MANAGEMENT: [
    {
      id: 1,
      title: 'Users',
      path: APP_ROUTES.USERS,
    },
  ],
  SBU_MANAGEMENT: [
    {
      id: 2,
      title: 'SBU Management',
      path: APP_ROUTES.SBU,
    },
  ],
  CLIENT_MANAGEMENT: [
    {
      id: 3,
      title: 'Client Management',
      path: APP_ROUTES.CLIENTS,
    },
  ],
  TEAM_MANAGEMENT: [
    {
      id: 4,
      title: 'Team Management',
      path: APP_ROUTES.TEAMS,
    },
  ],
  BANNER_MANAGEMENT: [
    {
      id: 5,
      title: 'Banner Management',
      path: APP_ROUTES.BANNERS,
    },
  ],
  RESIGNATION_MANAGEMENT: [
    {
      id: 6,
      title: 'Resignation Management',
      path: APP_ROUTES.RESIGNATIONS,
    },
  ],
  FLYER_MANAGEMENT: [
    {
      id: 8,
      title: 'Flyers',
      path: APP_ROUTES.FLYER,
    },
  ],
  ROLE_MANAGEMENT: [
    {
      id: 9,
      title: 'Configuration / Role Management',
      path: APP_ROUTES.ROLE_MANAGEMENT,
    },
  ],
  EDIT_USER: [
    {
      id: 12,
      title: 'Users/:username',
      path: APP_ROUTES.EDIT_USER,
    },
  ],
  BADGE_ASSIGNMENT: [
    {
      id: 10,
      title: 'Badges',
      path: APP_ROUTES.BADGE,
    },
    {
      id: 11,
      title: 'Assign-Badge',
      path: APP_ROUTES.BADGE_ASSIGNMENT,
    },
  ],
}
